version: "3.8"

services:
  mysql:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: saltynote
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql/data

  redis:
    image: 'redis:7.0-alpine'
    command: redis-server --requirepass 88888888
    ports:
      - '6379:6379'

  prometheus:
    image: prom/prometheus:v2.43.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:8.5.22
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

volumes:
  mysql_data:
