scrape_configs:
  - job_name: 'SaltyNote Service Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:8888' ]
        labels:
          application: 'SaltyNote Service'