# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the docker-compose for Database
        run: docker compose -f docker-compose.yml up -d
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to remote prod server
        run: scp -o "StrictHostKeyChecking no" target/service.jar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/note-service/
      - name: Restart service in remote prod server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl restart note.service"
